### ISSUE TITLE
Why not to bisect?

### ISSUE THREAD

**Issue by hinell** [kodanbce/aging-lines-vscode#1]
That's nice extension but did you ever hear about bisect?

https://git-scm.com/docs/git-bisect

**Comment by firoxer** [comment]
Yes. In my view, it's a different approach to the same matter, one that's less visual and more algorithmic. Do you see that there's more to it?

**Comment by hinell** [comment]
@firoxer I think it's a bit overkill... Good job anyway. Just saying!

**Comment by firoxer** [comment]
Alright, thanks for your input. Do try out Aging Lines the next time you encounter a mysterious bug and you should find out how it gives you new eyes when looking for the bug's origin. Vsego dobrogo!
